### PR TITLE
Normalize MAC address to lower case using prepareConfig

### PR DESCRIPTION
**Pull request by mwittig**
This will automatically normalize the MAC address to lower case before the device is instantiated. This way, user can also provide the MAC address using upper case letters.

See also https://forum.pimatic.org/topic/2327/pimatic-dash-button-problem

### CODE REVIEW

**Comment by michbeck100** [comment]
What about hyphen vs colon?

**Comment by mwittig** [comment]
Good point. Actually, there are even more format derivations https://community.spiceworks.com/topic/932330-mac-address-format-what-s-the-standard-why-don-t-vendors-stick-to-it

**Comment by mwittig** [comment]
Here is my proposal for simple MAC address validation and transformation.
https://jsfiddle.net/WittigMarcus/d7hyezwm/

It covers all cases of the aforementioned post, but MACs without leading '0's like ab-2-cd-4-ef-56﻿ will be regarded as an error. I'll extend my PR accordingly.

**Comment by michbeck100** [comment]
Perfect, thanks

**Pull request merged**
